### ISSUE TITLE
hello！I meet some problems when trying to test dog.jpg

### ISSUE THREAD

**Issue by goingwxj** [SherlockLiao/deploy-pytorch-model#1]
File "simple_request.py", line 38, in <module>
    predict_result(args.file)
  File "simple_request.py", line 20, in predict_result
    r = requests.post(PyTorch_REST_API_URL, files=payload).json()
  File "D:\ananconda\lib\site-packages\requests\models.py", line 885, in json
    return complexjson.loads(self.text, **kwargs)
  File "D:\ananconda\lib\json\__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "D:\ananconda\lib\json\decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "D:\ananconda\lib\json\decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

thank you for your help!

**Comment by lxztju** [comment]
have you solve this problem ? I also have this problem.

**Comment by Tetrix** [comment]
In order to solve the issue you need to add:
`results = (results[0].cpu().numpy(), results[1].cpu().numpy())`
after this line of code:
`results = torch.topk(preds.cpu().data, k=3, dim=1)`

Adding that fixed the issue for me.

**Comment by chl916185** [comment]
@L1aoXingyu 
在执行run_pytorch_server.py时，ｌｏａｄ_mode函数并未执行，当把加载模型的代码放到def predict():
中时，可得到结果，这个模型要一次加载怎么解决呢

**Comment by L1aoXingyu** [comment]
为什么`load_model`没有执行呢，在[这里](https://github.com/L1aoXingyu/deploy-pytorch-model/blob/master/run_pytorch_server.py#L102)确实会调用`load_model`这个函数

**Comment by chl916185** [comment]
我调试了代码，在ｐｒｅｄｉｃｔ函数中，全局变量ｍｏｄｅｌ为Ｎｏｎｅ,导致了https://github.com/L1aoXingyu/deploy-pytorch-model/issues/1#issue-445505132

**Comment by chl916185** [comment]
> 为什么`load_model`没有执行呢，在[这里](https://github.com/L1aoXingyu/deploy-pytorch-model/blob/master/run_pytorch_server.py#L102)确实会调用`load_model`这个函数

我重启了电脑就好了，谢谢您的代码
